//! This file is autogenerated from syntaxTree.ts.
import { uint } from "../../shims.ts";
import {
  AdditiveExpression,
  ArrayLiteral,
  ArrayType,
  AssignmentExpression,
  BindFlags,
  BindState,
  BooleanLiteral,
  CallExpression,
  ComparisonExpression,
  DeferStatement,
  Diagnostic,
  ElementAccessExpression,
  EnumDeclaration,
  EnumMember,
  EqualityExpression,
  Expression,
  ExpressionStatement,
  FuncDeclaration,
  Identifier,
  IfStatement,
  ImportDeclaration,
  IntegerLiteral,
  LogicalExpression,
  MethodDeclaration,
  MethodReceiver,
  MultiplicativeExpression,
  Operator,
  ParenthesizedExpression,
  PointerType,
  Program,
  PropertyAccessExpression,
  QualifiedName,
  ReturnStatement,
  SourceFile,
  Statement,
  StatementBlock,
  StringLiteral,
  StructDeclaration,
  StructLiteral,
  StructLiteralElement,
  StructMember,
  Symbol,
  SymbolTable,
  SyntaxKind,
  TextPosition,
  TypeNode,
  TypeReference,
  UnaryExpression,
  VarDeclaration,
  WhileStatement,
} from "./syntaxTree.ts";

export function makeTextPosition(line: uint, column: uint): TextPosition {
  return { line, column };
}

export interface MakeSymbolOptionalProps {
  parent?: Symbol;
  type?: Symbol;
  members?: SymbolTable;
}

export function makeSymbol(
  sourceFileName: string,
  name: string,
  flags: BindFlags,
  optional: MakeSymbolOptionalProps = {},
): Symbol {
  return {
    sourceFileName,
    name,
    flags,
    parent: optional.parent ?? undefined,
    type: optional.type ?? undefined,
    members: optional.members ?? undefined,
  };
}

export interface MakeProgramOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  diagnostics?: Diagnostic[];
}

export function makeProgram(
  entryFileName: string,
  sourceFiles: Record<string, SourceFile>,
  optional: MakeProgramOptionalProps = {},
): Program {
  return {
    kind: SyntaxKind.Program,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    locals: {},
    entryFileName,
    sourceFiles,
    diagnostics: optional.diagnostics ?? [],
  };
}

export interface MakeSourceFileOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeSourceFile(
  fileName: string,
  statements: Statement[],
  exports: SymbolTable,
  optional: MakeSourceFileOptionalProps = {},
): SourceFile {
  return {
    kind: SyntaxKind.SourceFile,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    locals: {},
    fileName,
    statements,
    exports,
  };
}

export interface MakeImportDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  alias?: Identifier;
}

export function makeImportDeclaration(
  module: StringLiteral,
  resolvedFileName: string,
  optional: MakeImportDeclarationOptionalProps = {},
): ImportDeclaration {
  return {
    kind: SyntaxKind.ImportDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    module,
    resolvedFileName,
    alias: optional.alias ?? undefined,
  };
}

export interface MakeVarDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  initializer?: Expression;
}

export function makeVarDeclaration(
  name: Identifier,
  type: TypeNode,
  optional: MakeVarDeclarationOptionalProps = {},
): VarDeclaration {
  return {
    kind: SyntaxKind.VarDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    type,
    initializer: optional.initializer ?? undefined,
  };
}

export interface MakeEnumDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  isExported?: boolean;
}

export function makeEnumDeclaration(
  name: Identifier,
  members: EnumMember[],
  optional: MakeEnumDeclarationOptionalProps = {},
): EnumDeclaration {
  return {
    kind: SyntaxKind.EnumDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    members,
    isExported: optional.isExported ?? false,
  };
}

export interface MakeEnumMemberOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  initializer?: Expression;
}

export function makeEnumMember(
  name: Identifier,
  optional: MakeEnumMemberOptionalProps = {},
): EnumMember {
  return {
    kind: SyntaxKind.EnumMember,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    initializer: optional.initializer ?? undefined,
  };
}

export interface MakeFuncDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  isExported?: boolean;
}

export function makeFuncDeclaration(
  name: Identifier,
  args: VarDeclaration[],
  returnType: TypeNode,
  body: StatementBlock,
  optional: MakeFuncDeclarationOptionalProps = {},
): FuncDeclaration {
  return {
    kind: SyntaxKind.FuncDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    locals: {},
    name,
    args,
    returnType,
    body,
    isExported: optional.isExported ?? false,
  };
}

export interface MakeMethodDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  isExported?: boolean;
}

export function makeMethodDeclaration(
  receiver: MethodReceiver,
  name: Identifier,
  args: VarDeclaration[],
  returnType: TypeNode,
  body: StatementBlock,
  optional: MakeMethodDeclarationOptionalProps = {},
): MethodDeclaration {
  return {
    kind: SyntaxKind.MethodDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    locals: {},
    receiver,
    name,
    args,
    returnType,
    body,
    isExported: optional.isExported ?? false,
  };
}

export interface MakeMethodReceiverOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeMethodReceiver(
  name: Identifier,
  type: TypeReference,
  optional: MakeMethodReceiverOptionalProps = {},
): MethodReceiver {
  return {
    kind: SyntaxKind.MethodReceiver,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    type,
  };
}

export interface MakeStructDeclarationOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  isExported?: boolean;
}

export function makeStructDeclaration(
  name: Identifier,
  members: StructMember[],
  optional: MakeStructDeclarationOptionalProps = {},
): StructDeclaration {
  return {
    kind: SyntaxKind.StructDeclaration,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    members,
    isExported: optional.isExported ?? false,
  };
}

export interface MakeStructMemberOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeStructMember(
  name: Identifier,
  type: Identifier,
  optional: MakeStructMemberOptionalProps = {},
): StructMember {
  return {
    kind: SyntaxKind.StructMember,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    type,
  };
}

export interface MakeExpressionStatementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeExpressionStatement(
  expression: Expression,
  optional: MakeExpressionStatementOptionalProps = {},
): ExpressionStatement {
  return {
    kind: SyntaxKind.ExpressionStatement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
  };
}

export interface MakeDeferStatementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeDeferStatement(
  body: Statement,
  optional: MakeDeferStatementOptionalProps = {},
): DeferStatement {
  return {
    kind: SyntaxKind.DeferStatement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    body,
  };
}

export interface MakeIfStatementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  else?: Statement;
}

export function makeIfStatement(
  condition: Expression,
  then: Statement,
  optional: MakeIfStatementOptionalProps = {},
): IfStatement {
  return {
    kind: SyntaxKind.IfStatement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    condition,
    then,
    else: optional.else ?? undefined,
  };
}

export interface MakeWhileStatementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeWhileStatement(
  condition: Expression,
  body: Statement,
  optional: MakeWhileStatementOptionalProps = {},
): WhileStatement {
  return {
    kind: SyntaxKind.WhileStatement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    condition,
    body,
  };
}

export interface MakeReturnStatementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeReturnStatement(
  expression: Expression,
  optional: MakeReturnStatementOptionalProps = {},
): ReturnStatement {
  return {
    kind: SyntaxKind.ReturnStatement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
  };
}

export interface MakeStatementBlockOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeStatementBlock(
  statements: Statement[],
  optional: MakeStatementBlockOptionalProps = {},
): StatementBlock {
  return {
    kind: SyntaxKind.StatementBlock,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    locals: {},
    statements,
  };
}

export interface MakeLogicalExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeLogicalExpression(
  lhs: Expression,
  operator: Operator.AmpersandAmpersand | Operator.BarBar,
  rhs: Expression,
  optional: MakeLogicalExpressionOptionalProps = {},
): LogicalExpression {
  return {
    kind: SyntaxKind.LogicalExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    lhs,
    operator,
    rhs,
  };
}

export interface MakeAssignmentExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeAssignmentExpression(
  name: Identifier,
  operator:
    | Operator.Equals
    | Operator.PlusEquals
    | Operator.MinusEquals
    | Operator.AsteriskEquals
    | Operator.SlashEquals,
  value: Expression,
  optional: MakeAssignmentExpressionOptionalProps = {},
): AssignmentExpression {
  return {
    kind: SyntaxKind.AssignmentExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    name,
    operator,
    value,
  };
}

export interface MakeEqualityExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeEqualityExpression(
  lhs: Expression,
  operator: Operator.EqualsEquals | Operator.ExclamationEquals,
  rhs: Expression,
  optional: MakeEqualityExpressionOptionalProps = {},
): EqualityExpression {
  return {
    kind: SyntaxKind.EqualityExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    lhs,
    operator,
    rhs,
  };
}

export interface MakeComparisonExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeComparisonExpression(
  lhs: Expression,
  operator: Operator.GreaterThan | Operator.GreaterThanEquals | Operator.LessThan | Operator.LessThanEquals,
  rhs: Expression,
  optional: MakeComparisonExpressionOptionalProps = {},
): ComparisonExpression {
  return {
    kind: SyntaxKind.ComparisonExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    lhs,
    operator,
    rhs,
  };
}

export interface MakeAdditiveExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeAdditiveExpression(
  lhs: Expression,
  operator: Operator.Plus | Operator.Minus,
  rhs: Expression,
  optional: MakeAdditiveExpressionOptionalProps = {},
): AdditiveExpression {
  return {
    kind: SyntaxKind.AdditiveExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    lhs,
    operator,
    rhs,
  };
}

export interface MakeMultiplicativeExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeMultiplicativeExpression(
  lhs: Expression,
  operator: Operator.Asterisk | Operator.Slash,
  rhs: Expression,
  optional: MakeMultiplicativeExpressionOptionalProps = {},
): MultiplicativeExpression {
  return {
    kind: SyntaxKind.MultiplicativeExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    lhs,
    operator,
    rhs,
  };
}

export interface MakeUnaryExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeUnaryExpression(
  operator: Operator.Ampersand | Operator.Asterisk | Operator.Exclamation | Operator.Minus,
  expression: Expression,
  optional: MakeUnaryExpressionOptionalProps = {},
): UnaryExpression {
  return {
    kind: SyntaxKind.UnaryExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    operator,
    expression,
  };
}

export interface MakeParenthesizedExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeParenthesizedExpression(
  expression: Expression,
  optional: MakeParenthesizedExpressionOptionalProps = {},
): ParenthesizedExpression {
  return {
    kind: SyntaxKind.ParenthesizedExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
  };
}

export interface MakeCallExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeCallExpression(
  expression: Expression,
  args: Expression[],
  optional: MakeCallExpressionOptionalProps = {},
): CallExpression {
  return {
    kind: SyntaxKind.CallExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
    args,
  };
}

export interface MakeElementAccessExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeElementAccessExpression(
  expression: Expression,
  argumentExpression: Expression,
  optional: MakeElementAccessExpressionOptionalProps = {},
): ElementAccessExpression {
  return {
    kind: SyntaxKind.ElementAccessExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
    argumentExpression,
  };
}

export interface MakePropertyAccessExpressionOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makePropertyAccessExpression(
  expression: Expression,
  name: Identifier,
  optional: MakePropertyAccessExpressionOptionalProps = {},
): PropertyAccessExpression {
  return {
    kind: SyntaxKind.PropertyAccessExpression,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
    name,
  };
}

export interface MakeArrayTypeOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeArrayType(
  elementType: TypeNode,
  optional: MakeArrayTypeOptionalProps = {},
): ArrayType {
  return {
    kind: SyntaxKind.ArrayType,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    elementType,
  };
}

export interface MakePointerTypeOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makePointerType(
  elementType: TypeNode,
  optional: MakePointerTypeOptionalProps = {},
): PointerType {
  return {
    kind: SyntaxKind.PointerType,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    elementType,
  };
}

export interface MakeTypeReferenceOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeTypeReference(
  typeName: QualifiedName | Identifier,
  optional: MakeTypeReferenceOptionalProps = {},
): TypeReference {
  return {
    kind: SyntaxKind.TypeReference,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    typeName,
  };
}

export interface MakeQualifiedNameOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeQualifiedName(
  left: Identifier,
  right: Identifier,
  optional: MakeQualifiedNameOptionalProps = {},
): QualifiedName {
  return {
    kind: SyntaxKind.QualifiedName,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    left,
    right,
  };
}

export interface MakeIdentifierOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeIdentifier(
  value: string,
  optional: MakeIdentifierOptionalProps = {},
): Identifier {
  return {
    kind: SyntaxKind.Identifier,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    value,
  };
}

export interface MakeArrayLiteralOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeArrayLiteral(
  elements: Expression[],
  optional: MakeArrayLiteralOptionalProps = {},
): ArrayLiteral {
  return {
    kind: SyntaxKind.ArrayLiteral,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    elements,
  };
}

export interface MakeStructLiteralOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeStructLiteral(
  elements: StructLiteralElement[],
  optional: MakeStructLiteralOptionalProps = {},
): StructLiteral {
  return {
    kind: SyntaxKind.StructLiteral,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    elements,
  };
}

export interface MakeStructLiteralElementOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
  name?: Identifier;
}

export function makeStructLiteralElement(
  expression: Expression,
  optional: MakeStructLiteralElementOptionalProps = {},
): StructLiteralElement {
  return {
    kind: SyntaxKind.StructLiteralElement,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    expression,
    name: optional.name ?? undefined,
  };
}

export interface MakeBooleanLiteralOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeBooleanLiteral(
  value: boolean,
  optional: MakeBooleanLiteralOptionalProps = {},
): BooleanLiteral {
  return {
    kind: SyntaxKind.BooleanLiteral,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    value,
  };
}

export interface MakeIntegerLiteralOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeIntegerLiteral(
  value: string,
  optional: MakeIntegerLiteralOptionalProps = {},
): IntegerLiteral {
  return {
    kind: SyntaxKind.IntegerLiteral,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    value,
  };
}

export interface MakeStringLiteralOptionalProps {
  startPos?: TextPosition;
  endPos?: TextPosition;
}

export function makeStringLiteral(
  value: string,
  optional: MakeStringLiteralOptionalProps = {},
): StringLiteral {
  return {
    kind: SyntaxKind.StringLiteral,
    startPos: optional.startPos ?? makeTextPosition(0, 0),
    endPos: optional.endPos ?? makeTextPosition(0, 0),
    bindState: BindState.Uninitialized,
    value,
  };
}
