//! This file is autogenerated from syntaxTree.ts.
import { BindFlags, BindState, Operator, SyntaxKind } from "./syntaxTree.ts";

export function nameofSyntaxKind(kind: SyntaxKind): string {
  switch (kind) {
    case SyntaxKind.AdditiveExpression:
      return "AdditiveExpression";
    case SyntaxKind.ArrayLiteral:
      return "ArrayLiteral";
    case SyntaxKind.ArrayType:
      return "ArrayType";
    case SyntaxKind.AssignmentExpression:
      return "AssignmentExpression";
    case SyntaxKind.BooleanLiteral:
      return "BooleanLiteral";
    case SyntaxKind.CallExpression:
      return "CallExpression";
    case SyntaxKind.ComparisonExpression:
      return "ComparisonExpression";
    case SyntaxKind.DeferStatement:
      return "DeferStatement";
    case SyntaxKind.ElementAccessExpression:
      return "ElementAccessExpression";
    case SyntaxKind.EnumDeclaration:
      return "EnumDeclaration";
    case SyntaxKind.EnumMember:
      return "EnumMember";
    case SyntaxKind.EqualityExpression:
      return "EqualityExpression";
    case SyntaxKind.ExpressionStatement:
      return "ExpressionStatement";
    case SyntaxKind.FuncArgument:
      return "FuncArgument";
    case SyntaxKind.FuncDeclaration:
      return "FuncDeclaration";
    case SyntaxKind.Identifier:
      return "Identifier";
    case SyntaxKind.IfStatement:
      return "IfStatement";
    case SyntaxKind.ImportDeclaration:
      return "ImportDeclaration";
    case SyntaxKind.IntegerLiteral:
      return "IntegerLiteral";
    case SyntaxKind.LogicalExpression:
      return "LogicalExpression";
    case SyntaxKind.MethodDeclaration:
      return "MethodDeclaration";
    case SyntaxKind.MethodReceiver:
      return "MethodReceiver";
    case SyntaxKind.MultiplicativeExpression:
      return "MultiplicativeExpression";
    case SyntaxKind.ParenthesizedExpression:
      return "ParenthesizedExpression";
    case SyntaxKind.PointerType:
      return "PointerType";
    case SyntaxKind.Program:
      return "Program";
    case SyntaxKind.PropertyAccessExpression:
      return "PropertyAccessExpression";
    case SyntaxKind.QualifiedName:
      return "QualifiedName";
    case SyntaxKind.ReturnStatement:
      return "ReturnStatement";
    case SyntaxKind.SourceFile:
      return "SourceFile";
    case SyntaxKind.Statement:
      return "Statement";
    case SyntaxKind.StatementBlock:
      return "StatementBlock";
    case SyntaxKind.StringLiteral:
      return "StringLiteral";
    case SyntaxKind.StructDeclaration:
      return "StructDeclaration";
    case SyntaxKind.StructLiteral:
      return "StructLiteral";
    case SyntaxKind.StructLiteralElement:
      return "StructLiteralElement";
    case SyntaxKind.StructMember:
      return "StructMember";
    case SyntaxKind.TypeReference:
      return "TypeReference";
    case SyntaxKind.UnaryExpression:
      return "UnaryExpression";
    case SyntaxKind.VarDeclaration:
      return "VarDeclaration";
    case SyntaxKind.WhileStatement:
      return "WhileStatement";
  }
}

export function nameofOperator(kind: Operator): string {
  switch (kind) {
    case Operator.Ampersand:
      return "Ampersand";
    case Operator.AmpersandAmpersand:
      return "AmpersandAmpersand";
    case Operator.Asterisk:
      return "Asterisk";
    case Operator.AsteriskEquals:
      return "AsteriskEquals";
    case Operator.BarBar:
      return "BarBar";
    case Operator.Equals:
      return "Equals";
    case Operator.EqualsEquals:
      return "EqualsEquals";
    case Operator.Exclamation:
      return "Exclamation";
    case Operator.ExclamationEquals:
      return "ExclamationEquals";
    case Operator.GreaterThan:
      return "GreaterThan";
    case Operator.GreaterThanEquals:
      return "GreaterThanEquals";
    case Operator.LessThan:
      return "LessThan";
    case Operator.LessThanEquals:
      return "LessThanEquals";
    case Operator.Minus:
      return "Minus";
    case Operator.MinusEquals:
      return "MinusEquals";
    case Operator.Plus:
      return "Plus";
    case Operator.PlusEquals:
      return "PlusEquals";
    case Operator.Slash:
      return "Slash";
    case Operator.SlashEquals:
      return "SlashEquals";
  }
}

export function nameofBindState(kind: BindState): string {
  switch (kind) {
    case BindState.Uninitialized:
      return "Uninitialized";
    case BindState.Initialized:
      return "Initialized";
    case BindState.Finished:
      return "Finished";
  }
}

export function nameofBindFlags(kind: BindFlags): string {
  switch (kind) {
    case BindFlags.None:
      return "None";
    case BindFlags.Builtin:
      return "Builtin";
    case BindFlags.Module:
      return "Module";
    case BindFlags.Type:
      return "Type";
    case BindFlags.Var:
      return "Var";
    case BindFlags.Enum:
      return "Enum";
    case BindFlags.EnumMember:
      return "EnumMember";
    case BindFlags.Func:
      return "Func";
    case BindFlags.Struct:
      return "Struct";
    case BindFlags.StructMember:
      return "StructMember";
    case BindFlags.Method:
      return "Method";
  }
}
