//! This file is autogenerated from syntaxTree.ts.
import { Expression, Statement, SyntaxKind, SyntaxNode, TypeNode } from "./syntaxTree.ts";

export function isExpression(node: SyntaxNode): node is Expression {
  return (
    node.kind == SyntaxKind.AdditiveExpression ||
    node.kind == SyntaxKind.ArrayLiteral ||
    node.kind == SyntaxKind.AssignmentExpression ||
    node.kind == SyntaxKind.BooleanLiteral ||
    node.kind == SyntaxKind.CallExpression ||
    node.kind == SyntaxKind.ComparisonExpression ||
    node.kind == SyntaxKind.ElementAccessExpression ||
    node.kind == SyntaxKind.EqualityExpression ||
    node.kind == SyntaxKind.Identifier ||
    node.kind == SyntaxKind.IntegerLiteral ||
    node.kind == SyntaxKind.LogicalExpression ||
    node.kind == SyntaxKind.MultiplicativeExpression ||
    node.kind == SyntaxKind.ParenthesizedExpression ||
    node.kind == SyntaxKind.PropertyAccessExpression ||
    node.kind == SyntaxKind.StringLiteral ||
    node.kind == SyntaxKind.StructLiteral ||
    node.kind == SyntaxKind.UnaryExpression
  );
}

export function isStatement(node: SyntaxNode): node is Statement {
  return (
    node.kind == SyntaxKind.DeferStatement ||
    node.kind == SyntaxKind.ExpressionStatement ||
    node.kind == SyntaxKind.IfStatement ||
    node.kind == SyntaxKind.ReturnStatement ||
    node.kind == SyntaxKind.WhileStatement
  );
}

export function isTypeNode(node: SyntaxNode): node is TypeNode {
  return (
    node.kind == SyntaxKind.ArrayType ||
    node.kind == SyntaxKind.PointerType ||
    node.kind == SyntaxKind.TypeReference
  );
}
