//! This file is autogenerated from syntaxTree.ts.
import {
  AdditiveExpression,
  ArrayLiteral,
  ArrayType,
  AssignmentExpression,
  BindNode,
  BooleanLiteral,
  CallExpression,
  ComparisonExpression,
  Declaration,
  DeferStatement,
  ElementAccessExpression,
  EnumDeclaration,
  EnumMember,
  EqualityExpression,
  Expression,
  ExpressionStatement,
  FuncDeclaration,
  Identifier,
  IfStatement,
  ImportDeclaration,
  IntegerLiteral,
  LogicalExpression,
  MethodDeclaration,
  MultiplicativeExpression,
  ParenthesizedExpression,
  PointerType,
  Program,
  PropertyAccessExpression,
  QualifiedName,
  Reference,
  ReturnStatement,
  Scope,
  SourceFile,
  Statement,
  StatementBlock,
  StringLiteral,
  StructDeclaration,
  StructLiteral,
  StructLiteralElement,
  StructMember,
  SyntaxKind,
  SyntaxNode,
  TypeNode,
  TypeReference,
  UnaryExpression,
  VarDeclaration,
  WhileStatement,
} from "./syntaxTree.ts";

export function isAdditiveExpression(node: SyntaxNode): node is AdditiveExpression {
  return node.kind == SyntaxKind.AdditiveExpression;
}

export function isArrayLiteral(node: SyntaxNode): node is ArrayLiteral {
  return node.kind == SyntaxKind.ArrayLiteral;
}

export function isArrayType(node: SyntaxNode): node is ArrayType {
  return node.kind == SyntaxKind.ArrayType;
}

export function isAssignmentExpression(node: SyntaxNode): node is AssignmentExpression {
  return node.kind == SyntaxKind.AssignmentExpression;
}

export function isBindNode(node: SyntaxNode): node is BindNode {
  return (
    node.kind == SyntaxKind.AdditiveExpression ||
    node.kind == SyntaxKind.ArrayLiteral ||
    node.kind == SyntaxKind.ArrayType ||
    node.kind == SyntaxKind.AssignmentExpression ||
    node.kind == SyntaxKind.BooleanLiteral ||
    node.kind == SyntaxKind.CallExpression ||
    node.kind == SyntaxKind.ComparisonExpression ||
    node.kind == SyntaxKind.ElementAccessExpression ||
    node.kind == SyntaxKind.EnumDeclaration ||
    node.kind == SyntaxKind.EnumMember ||
    node.kind == SyntaxKind.EqualityExpression ||
    node.kind == SyntaxKind.FuncDeclaration ||
    node.kind == SyntaxKind.Identifier ||
    node.kind == SyntaxKind.ImportDeclaration ||
    node.kind == SyntaxKind.IntegerLiteral ||
    node.kind == SyntaxKind.LogicalExpression ||
    node.kind == SyntaxKind.MethodDeclaration ||
    node.kind == SyntaxKind.MultiplicativeExpression ||
    node.kind == SyntaxKind.ParenthesizedExpression ||
    node.kind == SyntaxKind.PointerType ||
    node.kind == SyntaxKind.Program ||
    node.kind == SyntaxKind.PropertyAccessExpression ||
    node.kind == SyntaxKind.QualifiedName ||
    node.kind == SyntaxKind.SourceFile ||
    node.kind == SyntaxKind.StatementBlock ||
    node.kind == SyntaxKind.StringLiteral ||
    node.kind == SyntaxKind.StructDeclaration ||
    node.kind == SyntaxKind.StructLiteral ||
    node.kind == SyntaxKind.StructMember ||
    node.kind == SyntaxKind.TypeReference ||
    node.kind == SyntaxKind.UnaryExpression ||
    node.kind == SyntaxKind.VarDeclaration
  );
}

export function isBooleanLiteral(node: SyntaxNode): node is BooleanLiteral {
  return node.kind == SyntaxKind.BooleanLiteral;
}

export function isCallExpression(node: SyntaxNode): node is CallExpression {
  return node.kind == SyntaxKind.CallExpression;
}

export function isComparisonExpression(node: SyntaxNode): node is ComparisonExpression {
  return node.kind == SyntaxKind.ComparisonExpression;
}

export function isDeclaration(node: SyntaxNode): node is Declaration {
  return (
    node.kind == SyntaxKind.EnumDeclaration ||
    node.kind == SyntaxKind.EnumMember ||
    node.kind == SyntaxKind.FuncDeclaration ||
    node.kind == SyntaxKind.ImportDeclaration ||
    node.kind == SyntaxKind.MethodDeclaration ||
    node.kind == SyntaxKind.StructDeclaration ||
    node.kind == SyntaxKind.StructMember ||
    node.kind == SyntaxKind.VarDeclaration
  );
}

export function isDeferStatement(node: SyntaxNode): node is DeferStatement {
  return node.kind == SyntaxKind.DeferStatement;
}

export function isElementAccessExpression(node: SyntaxNode): node is ElementAccessExpression {
  return node.kind == SyntaxKind.ElementAccessExpression;
}

export function isEnumDeclaration(node: SyntaxNode): node is EnumDeclaration {
  return node.kind == SyntaxKind.EnumDeclaration;
}

export function isEnumMember(node: SyntaxNode): node is EnumMember {
  return node.kind == SyntaxKind.EnumMember;
}

export function isEqualityExpression(node: SyntaxNode): node is EqualityExpression {
  return node.kind == SyntaxKind.EqualityExpression;
}

export function isExpression(node: SyntaxNode): node is Expression {
  return (
    node.kind == SyntaxKind.AdditiveExpression ||
    node.kind == SyntaxKind.ArrayLiteral ||
    node.kind == SyntaxKind.AssignmentExpression ||
    node.kind == SyntaxKind.BooleanLiteral ||
    node.kind == SyntaxKind.CallExpression ||
    node.kind == SyntaxKind.ComparisonExpression ||
    node.kind == SyntaxKind.ElementAccessExpression ||
    node.kind == SyntaxKind.EqualityExpression ||
    node.kind == SyntaxKind.Identifier ||
    node.kind == SyntaxKind.IntegerLiteral ||
    node.kind == SyntaxKind.LogicalExpression ||
    node.kind == SyntaxKind.MultiplicativeExpression ||
    node.kind == SyntaxKind.ParenthesizedExpression ||
    node.kind == SyntaxKind.PropertyAccessExpression ||
    node.kind == SyntaxKind.StringLiteral ||
    node.kind == SyntaxKind.StructLiteral ||
    node.kind == SyntaxKind.UnaryExpression
  );
}

export function isExpressionStatement(node: SyntaxNode): node is ExpressionStatement {
  return node.kind == SyntaxKind.ExpressionStatement;
}

export function isFuncDeclaration(node: SyntaxNode): node is FuncDeclaration {
  return node.kind == SyntaxKind.FuncDeclaration;
}

export function isIdentifier(node: SyntaxNode): node is Identifier {
  return node.kind == SyntaxKind.Identifier;
}

export function isIfStatement(node: SyntaxNode): node is IfStatement {
  return node.kind == SyntaxKind.IfStatement;
}

export function isImportDeclaration(node: SyntaxNode): node is ImportDeclaration {
  return node.kind == SyntaxKind.ImportDeclaration;
}

export function isIntegerLiteral(node: SyntaxNode): node is IntegerLiteral {
  return node.kind == SyntaxKind.IntegerLiteral;
}

export function isLogicalExpression(node: SyntaxNode): node is LogicalExpression {
  return node.kind == SyntaxKind.LogicalExpression;
}

export function isMethodDeclaration(node: SyntaxNode): node is MethodDeclaration {
  return node.kind == SyntaxKind.MethodDeclaration;
}

export function isMultiplicativeExpression(node: SyntaxNode): node is MultiplicativeExpression {
  return node.kind == SyntaxKind.MultiplicativeExpression;
}

export function isParenthesizedExpression(node: SyntaxNode): node is ParenthesizedExpression {
  return node.kind == SyntaxKind.ParenthesizedExpression;
}

export function isPointerType(node: SyntaxNode): node is PointerType {
  return node.kind == SyntaxKind.PointerType;
}

export function isProgram(node: SyntaxNode): node is Program {
  return node.kind == SyntaxKind.Program;
}

export function isPropertyAccessExpression(node: SyntaxNode): node is PropertyAccessExpression {
  return node.kind == SyntaxKind.PropertyAccessExpression;
}

export function isQualifiedName(node: SyntaxNode): node is QualifiedName {
  return node.kind == SyntaxKind.QualifiedName;
}

export function isReference(node: SyntaxNode): node is Reference {
  return (
    node.kind == SyntaxKind.AdditiveExpression ||
    node.kind == SyntaxKind.ArrayLiteral ||
    node.kind == SyntaxKind.ArrayType ||
    node.kind == SyntaxKind.AssignmentExpression ||
    node.kind == SyntaxKind.BooleanLiteral ||
    node.kind == SyntaxKind.CallExpression ||
    node.kind == SyntaxKind.ComparisonExpression ||
    node.kind == SyntaxKind.ElementAccessExpression ||
    node.kind == SyntaxKind.EqualityExpression ||
    node.kind == SyntaxKind.Identifier ||
    node.kind == SyntaxKind.IntegerLiteral ||
    node.kind == SyntaxKind.LogicalExpression ||
    node.kind == SyntaxKind.MultiplicativeExpression ||
    node.kind == SyntaxKind.ParenthesizedExpression ||
    node.kind == SyntaxKind.PointerType ||
    node.kind == SyntaxKind.PropertyAccessExpression ||
    node.kind == SyntaxKind.QualifiedName ||
    node.kind == SyntaxKind.StringLiteral ||
    node.kind == SyntaxKind.StructLiteral ||
    node.kind == SyntaxKind.TypeReference ||
    node.kind == SyntaxKind.UnaryExpression
  );
}

export function isReturnStatement(node: SyntaxNode): node is ReturnStatement {
  return node.kind == SyntaxKind.ReturnStatement;
}

export function isScope(node: SyntaxNode): node is Scope {
  return (
    node.kind == SyntaxKind.FuncDeclaration ||
    node.kind == SyntaxKind.MethodDeclaration ||
    node.kind == SyntaxKind.Program ||
    node.kind == SyntaxKind.SourceFile ||
    node.kind == SyntaxKind.StatementBlock
  );
}

export function isSourceFile(node: SyntaxNode): node is SourceFile {
  return node.kind == SyntaxKind.SourceFile;
}

export function isStatement(node: SyntaxNode): node is Statement {
  return (
    node.kind == SyntaxKind.DeferStatement ||
    node.kind == SyntaxKind.ExpressionStatement ||
    node.kind == SyntaxKind.IfStatement ||
    node.kind == SyntaxKind.ReturnStatement ||
    node.kind == SyntaxKind.WhileStatement
  );
}

export function isStatementBlock(node: SyntaxNode): node is StatementBlock {
  return node.kind == SyntaxKind.StatementBlock;
}

export function isStringLiteral(node: SyntaxNode): node is StringLiteral {
  return node.kind == SyntaxKind.StringLiteral;
}

export function isStructDeclaration(node: SyntaxNode): node is StructDeclaration {
  return node.kind == SyntaxKind.StructDeclaration;
}

export function isStructLiteral(node: SyntaxNode): node is StructLiteral {
  return node.kind == SyntaxKind.StructLiteral;
}

export function isStructLiteralElement(node: SyntaxNode): node is StructLiteralElement {
  return node.kind == SyntaxKind.StructLiteralElement;
}

export function isStructMember(node: SyntaxNode): node is StructMember {
  return node.kind == SyntaxKind.StructMember;
}

export function isTypeNode(node: SyntaxNode): node is TypeNode {
  return (
    node.kind == SyntaxKind.ArrayType ||
    node.kind == SyntaxKind.PointerType ||
    node.kind == SyntaxKind.TypeReference
  );
}

export function isTypeReference(node: SyntaxNode): node is TypeReference {
  return node.kind == SyntaxKind.TypeReference;
}

export function isUnaryExpression(node: SyntaxNode): node is UnaryExpression {
  return node.kind == SyntaxKind.UnaryExpression;
}

export function isVarDeclaration(node: SyntaxNode): node is VarDeclaration {
  return node.kind == SyntaxKind.VarDeclaration;
}

export function isWhileStatement(node: SyntaxNode): node is WhileStatement {
  return node.kind == SyntaxKind.WhileStatement;
}
