//! This file is autogenerated from syntaxTree.ts.
import {
  AdditiveExpression,
  ArrayLiteral,
  ArrayType,
  AssignmentExpression,
  CallExpression,
  ComparisonExpression,
  DeferStatement,
  ElementAccessExpression,
  EnumDeclaration,
  EnumMember,
  EqualityExpression,
  ExpressionStatement,
  FunctionDeclaration,
  IfStatement,
  ImportDeclaration,
  LogicalExpression,
  MultiplicativeExpression,
  ParenthesizedExpression,
  PointerType,
  PropertyAccessExpression,
  QualifiedName,
  ReturnStatement,
  SourceFile,
  StatementBlock,
  StructDeclaration,
  StructLiteral,
  StructLiteralElement,
  StructMember,
  SyntaxKind,
  SyntaxNode,
  TypeReference,
  UnaryExpression,
  VariableDeclaration,
  WhileStatement,
} from "./syntaxTree.ts";
import { bool } from "../../shims.ts";

export type WalkCallback = (node: SyntaxNode, parent?: SyntaxNode) => bool;

export function walk(node: SyntaxNode, callback: WalkCallback): void {
  walkParent(node, callback);
}

function walkParent(node: SyntaxNode, callback: WalkCallback, parent?: SyntaxNode): void {
  // NOTE: The return value of callback indicates if we should keep descending further into the tree.
  if (callback(node, parent)) {
    walkChildren(node, callback);
  }
}

export function walkArray(nodes: SyntaxNode[], callback: WalkCallback): void {
  walkArrayParent(nodes, callback);
}

function walkArrayParent(nodes: SyntaxNode[], callback: WalkCallback, parent?: SyntaxNode): void {
  for (const node of nodes) {
    walkParent(node, callback, parent);
  }
}

export type WalkChildrenCallback = (node: SyntaxNode, parent: SyntaxNode) => bool;

export function walkChildren(node: SyntaxNode, callback: WalkChildrenCallback): void {
  switch (node.kind) {
    case SyntaxKind.SourceFile:
      {
        const sourceFile = <SourceFile> node;
        walkArrayParent(sourceFile.statements, <WalkCallback> callback, sourceFile);
      }
      break;
    case SyntaxKind.ImportDeclaration:
      {
        const importDeclaration = <ImportDeclaration> node;
        if (importDeclaration.alias) {
          walkParent(importDeclaration.alias, <WalkCallback> callback, importDeclaration);
        }
        walkParent(importDeclaration.module, <WalkCallback> callback, importDeclaration);
      }
      break;
    case SyntaxKind.VariableDeclaration:
      {
        const variableDeclaration = <VariableDeclaration> node;
        walkParent(variableDeclaration.name, <WalkCallback> callback, variableDeclaration);
        walkParent(variableDeclaration.type, <WalkCallback> callback, variableDeclaration);
        if (variableDeclaration.initializer) {
          walkParent(variableDeclaration.initializer, <WalkCallback> callback, variableDeclaration);
        }
      }
      break;
    case SyntaxKind.EnumDeclaration:
      {
        const enumDeclaration = <EnumDeclaration> node;
        walkParent(enumDeclaration.name, <WalkCallback> callback, enumDeclaration);
        walkArrayParent(enumDeclaration.members, <WalkCallback> callback, enumDeclaration);
      }
      break;
    case SyntaxKind.EnumMember:
      {
        const enumMember = <EnumMember> node;
        walkParent(enumMember.name, <WalkCallback> callback, enumMember);
        if (enumMember.initializer) {
          walkParent(enumMember.initializer, <WalkCallback> callback, enumMember);
        }
      }
      break;
    case SyntaxKind.FunctionDeclaration:
      {
        const functionDeclaration = <FunctionDeclaration> node;
        walkParent(functionDeclaration.name, <WalkCallback> callback, functionDeclaration);
        walkArrayParent(functionDeclaration.arguments, <WalkCallback> callback, functionDeclaration);
        walkParent(functionDeclaration.returnType, <WalkCallback> callback, functionDeclaration);
        walkParent(functionDeclaration.body, <WalkCallback> callback, functionDeclaration);
      }
      break;
    case SyntaxKind.StructDeclaration:
      {
        const structDeclaration = <StructDeclaration> node;
        walkParent(structDeclaration.name, <WalkCallback> callback, structDeclaration);
        walkArrayParent(structDeclaration.members, <WalkCallback> callback, structDeclaration);
      }
      break;
    case SyntaxKind.StructMember:
      {
        const structMember = <StructMember> node;
        walkParent(structMember.name, <WalkCallback> callback, structMember);
        walkParent(structMember.type, <WalkCallback> callback, structMember);
      }
      break;
    case SyntaxKind.ExpressionStatement:
      {
        const expressionStatement = <ExpressionStatement> node;
        walkParent(expressionStatement.expression, <WalkCallback> callback, expressionStatement);
      }
      break;
    case SyntaxKind.DeferStatement:
      {
        const deferStatement = <DeferStatement> node;
        walkParent(deferStatement.body, <WalkCallback> callback, deferStatement);
      }
      break;
    case SyntaxKind.IfStatement:
      {
        const ifStatement = <IfStatement> node;
        walkParent(ifStatement.condition, <WalkCallback> callback, ifStatement);
        walkParent(ifStatement.then, <WalkCallback> callback, ifStatement);
        if (ifStatement.else) {
          walkParent(ifStatement.else, <WalkCallback> callback, ifStatement);
        }
      }
      break;
    case SyntaxKind.WhileStatement:
      {
        const whileStatement = <WhileStatement> node;
        walkParent(whileStatement.condition, <WalkCallback> callback, whileStatement);
        walkParent(whileStatement.body, <WalkCallback> callback, whileStatement);
      }
      break;
    case SyntaxKind.ReturnStatement:
      {
        const returnStatement = <ReturnStatement> node;
        walkParent(returnStatement.expression, <WalkCallback> callback, returnStatement);
      }
      break;
    case SyntaxKind.StatementBlock:
      {
        const statementBlock = <StatementBlock> node;
        walkArrayParent(statementBlock.statements, <WalkCallback> callback, statementBlock);
      }
      break;
    case SyntaxKind.LogicalExpression:
      {
        const logicalExpression = <LogicalExpression> node;
        walkParent(logicalExpression.lhs, <WalkCallback> callback, logicalExpression);
        walkParent(logicalExpression.rhs, <WalkCallback> callback, logicalExpression);
      }
      break;
    case SyntaxKind.AssignmentExpression:
      {
        const assignmentExpression = <AssignmentExpression> node;
        walkParent(assignmentExpression.name, <WalkCallback> callback, assignmentExpression);
      }
      break;
    case SyntaxKind.EqualityExpression:
      {
        const equalityExpression = <EqualityExpression> node;
        walkParent(equalityExpression.lhs, <WalkCallback> callback, equalityExpression);
        walkParent(equalityExpression.rhs, <WalkCallback> callback, equalityExpression);
      }
      break;
    case SyntaxKind.ComparisonExpression:
      {
        const comparisonExpression = <ComparisonExpression> node;
        walkParent(comparisonExpression.lhs, <WalkCallback> callback, comparisonExpression);
        walkParent(comparisonExpression.rhs, <WalkCallback> callback, comparisonExpression);
      }
      break;
    case SyntaxKind.AdditiveExpression:
      {
        const additiveExpression = <AdditiveExpression> node;
        walkParent(additiveExpression.lhs, <WalkCallback> callback, additiveExpression);
        walkParent(additiveExpression.rhs, <WalkCallback> callback, additiveExpression);
      }
      break;
    case SyntaxKind.MultiplicativeExpression:
      {
        const multiplicativeExpression = <MultiplicativeExpression> node;
        walkParent(multiplicativeExpression.lhs, <WalkCallback> callback, multiplicativeExpression);
        walkParent(multiplicativeExpression.rhs, <WalkCallback> callback, multiplicativeExpression);
      }
      break;
    case SyntaxKind.UnaryExpression:
      {
        const unaryExpression = <UnaryExpression> node;
        walkParent(unaryExpression.expression, <WalkCallback> callback, unaryExpression);
      }
      break;
    case SyntaxKind.ParenthesizedExpression:
      {
        const parenthesizedExpression = <ParenthesizedExpression> node;
        walkParent(parenthesizedExpression.expression, <WalkCallback> callback, parenthesizedExpression);
      }
      break;
    case SyntaxKind.CallExpression:
      {
        const callExpression = <CallExpression> node;
        walkParent(callExpression.expression, <WalkCallback> callback, callExpression);
        walkArrayParent(callExpression.arguments, <WalkCallback> callback, callExpression);
      }
      break;
    case SyntaxKind.ElementAccessExpression:
      {
        const elementAccessExpression = <ElementAccessExpression> node;
        walkParent(elementAccessExpression.expression, <WalkCallback> callback, elementAccessExpression);
        walkParent(elementAccessExpression.argumentExpression, <WalkCallback> callback, elementAccessExpression);
      }
      break;
    case SyntaxKind.PropertyAccessExpression:
      {
        const propertyAccessExpression = <PropertyAccessExpression> node;
        walkParent(propertyAccessExpression.expression, <WalkCallback> callback, propertyAccessExpression);
        walkParent(propertyAccessExpression.name, <WalkCallback> callback, propertyAccessExpression);
      }
      break;
    case SyntaxKind.ArrayType:
      {
        const arrayType = <ArrayType> node;
        walkParent(arrayType.elementType, <WalkCallback> callback, arrayType);
      }
      break;
    case SyntaxKind.PointerType:
      {
        const pointerType = <PointerType> node;
        walkParent(pointerType.elementType, <WalkCallback> callback, pointerType);
      }
      break;
    case SyntaxKind.TypeReference:
      {
        const typeReference = <TypeReference> node;
        walkParent(typeReference.typeName, <WalkCallback> callback, typeReference);
      }
      break;
    case SyntaxKind.QualifiedName:
      {
        const qualifiedName = <QualifiedName> node;
        walkParent(qualifiedName.left, <WalkCallback> callback, qualifiedName);
        walkParent(qualifiedName.right, <WalkCallback> callback, qualifiedName);
      }
      break;
    case SyntaxKind.ArrayLiteral:
      {
        const arrayLiteral = <ArrayLiteral> node;
        walkArrayParent(arrayLiteral.elements, <WalkCallback> callback, arrayLiteral);
      }
      break;
    case SyntaxKind.StructLiteral:
      {
        const structLiteral = <StructLiteral> node;
        walkArrayParent(structLiteral.elements, <WalkCallback> callback, structLiteral);
      }
      break;
    case SyntaxKind.StructLiteralElement:
      {
        const structLiteralElement = <StructLiteralElement> node;
        if (structLiteralElement.name) {
          walkParent(structLiteralElement.name, <WalkCallback> callback, structLiteralElement);
        }
        walkParent(structLiteralElement.expression, <WalkCallback> callback, structLiteralElement);
      }
      break;
  }
}
