//! This file is autogenerated from syntaxTree.ts.
import { uint, uint32 } from "../shims.ts";
import { generateId, IDType } from "./ids.ts";
import {
  EnumMemberSymbol,
  EnumSymbol,
  FuncSymbol,
  ImportSymbol,
  MethodReceiverSymbol,
  MethodSymbol,
  StructMemberSymbol,
  StructSymbol,
  SymbolFlags,
  SymbolKind,
  SymbolTable,
  TypeSymbol,
  VarSymbol,
} from "./symbols.ts";

export interface MakeEnumSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeEnumSymbol(
  name: string,
  optional: MakeEnumSymbolOptionalProps = {},
): EnumSymbol {
  return {
    kind: SymbolKind.Enum,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeEnumMemberSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
}

export function makeEnumMemberSymbol(
  name: string,
  optional: MakeEnumMemberSymbolOptionalProps = {},
): EnumMemberSymbol {
  return {
    kind: SymbolKind.EnumMember,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
  };
}

export interface MakeFuncSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  beginVaradicArgsIndex?: uint;
}

export function makeFuncSymbol(
  name: string,
  optional: MakeFuncSymbolOptionalProps = {},
): FuncSymbol {
  return {
    kind: SymbolKind.Func,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    beginVaradicArgsIndex: optional.beginVaradicArgsIndex ?? 0,
  };
}

export interface MakeImportSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeImportSymbol(
  name: string,
  optional: MakeImportSymbolOptionalProps = {},
): ImportSymbol {
  return {
    kind: SymbolKind.Import,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeMethodSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  beginVaradicArgsIndex?: uint;
}

export function makeMethodSymbol(
  name: string,
  optional: MakeMethodSymbolOptionalProps = {},
): MethodSymbol {
  return {
    kind: SymbolKind.Method,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    beginVaradicArgsIndex: optional.beginVaradicArgsIndex ?? 0,
  };
}

export interface MakeMethodReceiverSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeMethodReceiverSymbol(
  name: string,
  optional: MakeMethodReceiverSymbolOptionalProps = {},
): MethodReceiverSymbol {
  return {
    kind: SymbolKind.MethodReceiver,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeStructSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeStructSymbol(
  name: string,
  optional: MakeStructSymbolOptionalProps = {},
): StructSymbol {
  return {
    kind: SymbolKind.Struct,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeStructMemberSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeStructMemberSymbol(
  name: string,
  optional: MakeStructMemberSymbolOptionalProps = {},
): StructMemberSymbol {
  return {
    kind: SymbolKind.StructMember,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeTypeSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
  members?: SymbolTable;
}

export function makeTypeSymbol(
  name: string,
  optional: MakeTypeSymbolOptionalProps = {},
): TypeSymbol {
  return {
    kind: SymbolKind.Type,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
    members: optional.members ?? {},
  };
}

export interface MakeVarSymbolOptionalProps {
  id?: uint32;
  flags?: uint;
}

export function makeVarSymbol(
  name: string,
  optional: MakeVarSymbolOptionalProps = {},
): VarSymbol {
  return {
    kind: SymbolKind.Var,
    name,
    id: optional.id ?? generateId(IDType.Symbol),
    flags: optional.flags ?? SymbolFlags.None,
  };
}
