//! This file is autogenerated from syntaxTree.ts.
import {
  CallableSymbol,
  EnumMemberSymbol,
  EnumSymbol,
  ExternFuncSymbol,
  FuncSymbol,
  ImportSymbol,
  MethodReceiverSymbol,
  MethodSymbol,
  StructMemberSymbol,
  StructSymbol,
  Symbol,
  SymbolKind,
  SymbolWithDeclaration,
  SymbolWithMembers,
  TypeSymbol,
  VarSymbol,
} from "./symbols.ts";
import { Declaration } from "./syntaxTree.ts";

export function isCallableSymbol(symbol: Symbol | null): symbol is CallableSymbol {
  return symbol != null && (
    symbol.kind == SymbolKind.ExternFunc ||
    symbol.kind == SymbolKind.Func ||
    symbol.kind == SymbolKind.Method
  );
}

export function isEnumMemberSymbol(symbol: Symbol | null): symbol is EnumMemberSymbol {
  return symbol != null && symbol.kind == SymbolKind.EnumMember;
}

export function isEnumSymbol(symbol: Symbol | null): symbol is EnumSymbol {
  return symbol != null && symbol.kind == SymbolKind.Enum;
}

export function isExternFuncSymbol(symbol: Symbol | null): symbol is ExternFuncSymbol {
  return symbol != null && symbol.kind == SymbolKind.ExternFunc;
}

export function isFuncSymbol(symbol: Symbol | null): symbol is FuncSymbol {
  return symbol != null && symbol.kind == SymbolKind.Func;
}

export function isImportSymbol(symbol: Symbol | null): symbol is ImportSymbol {
  return symbol != null && symbol.kind == SymbolKind.Import;
}

export function isMethodReceiverSymbol(symbol: Symbol | null): symbol is MethodReceiverSymbol {
  return symbol != null && symbol.kind == SymbolKind.MethodReceiver;
}

export function isMethodSymbol(symbol: Symbol | null): symbol is MethodSymbol {
  return symbol != null && symbol.kind == SymbolKind.Method;
}

export function isStructMemberSymbol(symbol: Symbol | null): symbol is StructMemberSymbol {
  return symbol != null && symbol.kind == SymbolKind.StructMember;
}

export function isStructSymbol(symbol: Symbol | null): symbol is StructSymbol {
  return symbol != null && symbol.kind == SymbolKind.Struct;
}

export function isSymbolWithDeclaration(symbol: Symbol | null): symbol is SymbolWithDeclaration<Declaration<Symbol>> {
  return symbol != null && (
    symbol.kind == SymbolKind.EnumMember ||
    symbol.kind == SymbolKind.Enum ||
    symbol.kind == SymbolKind.ExternFunc ||
    symbol.kind == SymbolKind.Func ||
    symbol.kind == SymbolKind.Import ||
    symbol.kind == SymbolKind.MethodReceiver ||
    symbol.kind == SymbolKind.Method ||
    symbol.kind == SymbolKind.StructMember ||
    symbol.kind == SymbolKind.Struct ||
    symbol.kind == SymbolKind.Type ||
    symbol.kind == SymbolKind.Var
  );
}

export function isSymbolWithMembers(symbol: Symbol | null): symbol is SymbolWithMembers {
  return symbol != null && (
    symbol.kind == SymbolKind.Enum ||
    symbol.kind == SymbolKind.Import ||
    symbol.kind == SymbolKind.MethodReceiver ||
    symbol.kind == SymbolKind.StructMember ||
    symbol.kind == SymbolKind.Struct ||
    symbol.kind == SymbolKind.Type
  );
}

export function isTypeSymbol(symbol: Symbol | null): symbol is TypeSymbol {
  return symbol != null && symbol.kind == SymbolKind.Type;
}

export function isVarSymbol(symbol: Symbol | null): symbol is VarSymbol {
  return symbol != null && symbol.kind == SymbolKind.Var;
}
