#!/usr/bin/env -S deno run -RW --allow-run
import { join, resolve } from "node:path";
import { EOL } from "node:os";
import { readFile, writeFile } from "node:fs/promises";
import { argv, exit } from "node:process";
import { makeOutputWriter, OutputWriter } from "../src/outputWriter.ts";
import { int } from "../src/shims.ts";
import { firstLetterToLower } from "../src/utils.ts";
import { formatFile } from "./utils.ts";

const ROOT_PATH = resolve(import.meta.dirname!, "..");

const BASE_NODES = [
  "Expression",
  "TypeNode",
];

const TYPE_GUARDS_NOT_TO_EMIT = [
  "Diagnostic",
  "SyntaxNode",
  "Symbol",
  "TextPosition",
];

main(argv.slice(2)).then(exit);

async function main(_argv: string[]): Promise<int> {
  const syntaxTreeContents = (await readFile(join(ROOT_PATH, "src", "ast", "syntaxTree.ts"), "utf-8"))
    .split(EOL)
    .map((x) => x.trim());

  await writeAstTypeGuards(syntaxTreeContents);
  await writeAstWalk(syntaxTreeContents);
  await writeAstNameof(syntaxTreeContents);
  await writeAstFactories(syntaxTreeContents);

  return 0;
}

async function writeAndFormatFile(path: string, output: OutputWriter): Promise<void> {
  await writeFile(path, output.toString());
  await formatFile(path);
}

function createAstOutputWriter(): OutputWriter {
  const output = makeOutputWriter();
  output.appendLine("//! This file is autogenerated from syntaxTree.ts.");
  return output;
}

async function writeAstTypeGuards(syntaxTreeContents: string[]): Promise<void> {
  const output = createAstOutputWriter();

  const typeGuardsToEmit: string[] = [];
  const typeMap: Record<string, string[]> = {};
  const baseNodeInterfaces: Record<string, string[]> = Object.fromEntries(BASE_NODES.map((x) => [x, []]));

  for (const line of syntaxTreeContents) {
    if (line.startsWith("export interface ")) {
      const parts = line.split(" ");

      const interfaceName = parts[2];
      if (!TYPE_GUARDS_NOT_TO_EMIT.includes(interfaceName)) {
        typeGuardsToEmit.push(interfaceName);
      }

      if (parts[3] == "extends") {
        const extendedInterfaces = parts.slice(4)
          .filter((x) => x != "{")
          .map((x) => x.endsWith(",") ? x.substring(0, x.length - 1) : x);

        for (const extendedInterface of extendedInterfaces) {
          const isBaseNode = BASE_NODES.includes(extendedInterface);
          if (!isBaseNode) {
            if (typeMap[extendedInterface] == undefined) {
              typeMap[extendedInterface] = [];
            }

            typeMap[extendedInterface].push(interfaceName);
          } else if (isBaseNode) {
            baseNodeInterfaces[extendedInterface].push(interfaceName);
          }
        }
      }
    }
  }

  typeMap["Expression"] = baseNodeInterfaces["Expression"];
  typeMap["TypeNode"] = baseNodeInterfaces["TypeNode"];

  for (const key of Object.keys(typeMap)) {
    for (const baseNode of BASE_NODES) {
      if (typeMap[key].includes(baseNode)) {
        typeMap[key] = [...new Set([...typeMap[key].filter((x) => x != baseNode), ...baseNodeInterfaces[baseNode]])];
      }
    }
  }

  output.appendLine(`import { SyntaxKind, SyntaxNode, ${typeGuardsToEmit.join(", ")} } from "./syntaxTree.ts";`);
  output.appendLine();

  typeGuardsToEmit.sort();
  for (const typeGuard of typeGuardsToEmit) {
    output.appendLine(`export function is${typeGuard}(node: SyntaxNode): node is ${typeGuard} {`);
    output.indent();

    const kinds = typeMap[typeGuard]?.toSorted();
    if (kinds) {
      output.appendLine("return (");
      output.indent();

      for (let i = 0; i < kinds.length; i += 1) {
        if (i != 0) {
          output.append("|| ");
        }

        output.appendLine(`node.kind == SyntaxKind.${kinds[i]}`);
      }

      output.unindent();
      output.appendLine(");");
    } else {
      output.appendLine(`return node.kind == SyntaxKind.${typeGuard};`);
    }

    output.unindent();
    output.appendLine("}");
    output.appendLine();
  }

  await writeAndFormatFile(join(ROOT_PATH, "src", "ast", "typeGuards.ts"), output);
}

async function writeAstWalk(syntaxTreeContents: string[]): Promise<void> {
  const output = createAstOutputWriter();

  const importPlaceholder = output.createPlaceholder();
  importPlaceholder.append("import { SyntaxKind, SyntaxNode");

  output.appendLine(
    `import { bool } from "../shims.ts";

/**
 * @return Indicates whether or not descending further into the tree should continue.
 */
export type WalkCallback = (node: SyntaxNode, parent?: SyntaxNode) => bool;

export function walk(node: SyntaxNode, callback: WalkCallback): void {
  walkParent(node, callback);
}

function walkParent(node: SyntaxNode, callback: WalkCallback, parent?: SyntaxNode): void {
  // NOTE: The return value of callback indicates if we should keep descending further into the tree.
  if (callback(node, parent)) {
    walkChildren(node, callback);
  }
}

function walkArrayParent(nodes: SyntaxNode[], callback: WalkCallback, parent?: SyntaxNode): void {
  for (const node of nodes) {
    walkParent(node, callback, parent);
  }
}

function walkRecordParent(nodes: Record<string, SyntaxNode>, callback: WalkCallback, parent?: SyntaxNode): void {
  for (const node of Object.values(nodes)) {
    walkParent(node, callback, parent);
  }
}

export type WalkChildrenCallback = (node: SyntaxNode, parent: SyntaxNode) => bool;

export function walkChildren(node: SyntaxNode, callback: WalkChildrenCallback): void {
  switch (node.kind) {
`,
  );

  output.indent();
  output.indent();
  let interfaceName: string | null = null;
  let caseBlockIsOutput = false;
  for (const line of syntaxTreeContents) {
    if (line.trim().startsWith("//")) {
      continue;
    }

    if (interfaceName == null && line.startsWith("export interface ") && !line.endsWith("{}")) {
      const parts = line.split(" ");
      interfaceName = parts[2];

      if (
        ["TextPosition", "Diagnostic", "SyntaxNode", "BlockScope", "Declaration", "Symbol", "BindNode", "Scope"]
          .includes(interfaceName)
      ) {
        interfaceName = null;
        continue;
      }
    }

    if (interfaceName != null) {
      if (line.includes(":")) {
        const parts = line.split(" ");
        let propertyName = parts[0].replaceAll(":", "");

        if (
          [
            "diagnostics",
            "endPos",
            "exports",
            "fileName",
            "isExported",
            "kind",
            "locals",
            "operator",
            "startPos",
            "symbol?",
            "value",
          ]
            .includes(
              propertyName,
            )
        ) {
          continue;
        }

        const type = parts[1].substring(0, parts[1].length - 1);

        if (type == "string") {
          continue;
        }

        const interfaceVariableName = firstLetterToLower(interfaceName);

        if (!caseBlockIsOutput) {
          output.appendLine(`case SyntaxKind.${interfaceName}: {`);
          output.indent();
          output.appendLine(`const ${interfaceVariableName} = <${interfaceName}>node;`);
          caseBlockIsOutput = true;

          importPlaceholder.append(`, ${interfaceName}`);
        }

        let isOptional = false;
        if (propertyName.endsWith("?")) {
          propertyName = propertyName.replaceAll("?", "");
          output.appendLine(`if (${interfaceVariableName}.${propertyName}) {`);
          output.indent();
          isOptional = true;
        }

        let walkFunc = "walkParent";
        if (type.endsWith("[]")) {
          walkFunc = "walkArrayParent";
        } else if (type.startsWith("Record<")) {
          walkFunc = "walkRecordParent";
        }

        output.appendLine(
          `${walkFunc}(${interfaceVariableName}.${propertyName}, <WalkCallback>callback, ${interfaceVariableName});`,
        );

        if (isOptional) {
          output.append("}");
          output.unindent();
        }
      } else if (line.startsWith("}")) {
        if (caseBlockIsOutput) {
          output.appendLine("} break;");
          output.unindent();
        }
        interfaceName = null;
        caseBlockIsOutput = false;
      }
    }
  }
  output.unindent();
  output.appendLine("}");

  output.unindent();
  output.appendLine("}");

  importPlaceholder.append(`} from "./syntaxTree.ts";`);

  await writeAndFormatFile(join(ROOT_PATH, "src", "ast", "walk.ts"), output);
}

async function writeAstNameof(syntaxTreeContents: string[]): Promise<void> {
  const output = createAstOutputWriter();

  // Extract enum names and their values
  const enums: Record<string, string[]> = {};
  let currentEnumName: string | null = null;

  for (const line of syntaxTreeContents) {
    if (line.startsWith("export enum ")) {
      currentEnumName = line.split(" ")[2];
      enums[currentEnumName] = [];
    } else if (currentEnumName && line.startsWith("}")) {
      currentEnumName = null;
    } else if (currentEnumName && line.includes("=")) {
      // Handle enum with explicit values
      const parts = line.split("=");
      const enumValue = parts[0].trim();
      enums[currentEnumName].push(enumValue);
    } else if (currentEnumName && line.endsWith(",")) {
      // Handle regular enum without explicit values
      const enumValue = line.substring(0, line.length - 1).trim();
      enums[currentEnumName].push(enumValue);
    }
  }

  output.appendLine(`import { ${Object.keys(enums).toSorted().join(", ")} } from "./syntaxTree.ts";`);
  output.appendLine();

  // Generate nameof functions for each enum
  for (const [enumName, values] of Object.entries(enums)) {
    output.appendLine(`export function nameof${enumName}(kind: ${enumName}): string {`);
    output.indent();
    output.appendLine("switch (kind) {");
    output.indent();

    for (const value of values) {
      output.appendLine(`case ${enumName}.${value}: return "${value}";`);
    }

    output.unindent();
    output.appendLine("}");
    output.unindent();
    output.appendLine("}");
    output.appendLine();
  }

  await writeAndFormatFile(join(ROOT_PATH, "src", "ast", "nameof.ts"), output);
}

async function writeAstFactories(syntaxTreeContents: string[]): Promise<void> {
  const DO_NOT_IMPORT = [
    "boolean",
    "int",
    "int32",
    "string",
    "uint",
    "uint32",
  ];
  const EXCLUDE_INTERFACES = [
    "Declaration",
    "Diagnostic",
    "Expression",
    "Reference",
    "Scope",
    "Statement",
    "SyntaxNode",
    "TextPosition",
    "TypeNode",
  ];
  const EXCLUDE_PROPS = ["kind"];
  const ALWAYS_OPTIONAL_PROPS = ["diagnostics", "isExported"];
  const OPTIONAL_DEFAULT_VALUES: Record<string, string> = {
    "diagnostics": "[]",
    "isExported": "false",
  };

  let interfaceName: string | null = null;
  let collectedLine = "";

  const syntaxTreeImports: string[] = ["BindState", "Operator", "SourceFile", "SyntaxKind", "TextPosition"];
  const factories: Record<string, {
    extends: string[];
    required: Record<string, string>;
    optional: Record<string, string>;
  }> = {};

  for (let line of syntaxTreeContents) {
    line = line.trim();

    if (line.startsWith("//")) {
      continue;
    }

    if (interfaceName == null && line.startsWith("export interface ")) {
      const parts = line.split(" ");

      interfaceName = parts[2];

      if (EXCLUDE_INTERFACES.includes(interfaceName)) {
        interfaceName = null;
        continue;
      }

      factories[interfaceName] = {
        extends: [],
        required: {},
        optional: {},
      };

      if (parts[3] == "extends") {
        for (let i = 4; i < parts.length - 1; i += 1) {
          let extended = parts[i];
          if (extended.endsWith(",")) {
            extended = extended.substring(0, extended.length - 1);
          }
          factories[interfaceName].extends.push(extended);
        }
      }

      if (!syntaxTreeImports.includes(interfaceName)) {
        syntaxTreeImports.push(interfaceName);
      }
    } else if (interfaceName != null) {
      if (line.startsWith("}")) {
        interfaceName = null;
        continue;
      }

      collectedLine += line;

      if (collectedLine.trimEnd().endsWith(";")) {
        let [name, type] = collectedLine.split(":");
        collectedLine = "";

        if (EXCLUDE_PROPS.includes(name)) {
          continue;
        }

        type = type.trim();
        if (type.endsWith(";")) {
          type = type.substring(0, type.length - 1);
        }
        if (type.startsWith("| ")) {
          type = type.substring("| ".length);
        }

        if (ALWAYS_OPTIONAL_PROPS.includes(name) || name.endsWith("?")) {
          if (name.endsWith("?")) {
            name = name.substring(0, name.length - 1);
          }
          factories[interfaceName].optional[name] = type;
        } else {
          factories[interfaceName].required[name] = type;
        }

        if (!DO_NOT_IMPORT.includes(type) && !type.includes("|") && !type.startsWith("Record<")) {
          if (type.endsWith("[]")) {
            type = type.substring(0, type.length - "[]".length);
          }

          if (!syntaxTreeImports.includes(type)) {
            syntaxTreeImports.push(type);
          }
        }
      }
    }
  }

  const output = createAstOutputWriter();
  output.appendLine(`import { uint, uint32 } from "../shims.ts";`);
  output.appendLine(`import { ${syntaxTreeImports.toSorted().join(", ")} } from "./syntaxTree.ts";`);
  output.appendLine();
  output.appendLine(`export function makeTextPosition(line: uint, column: uint): TextPosition {
    return { line, column };
  }`);
  output.appendLine();

  for (const [name, props] of Object.entries(factories)) {
    console.info(name, props);

    output.appendLine(`export interface Make${name}OptionalProps {`);

    if (name != "Symbol") {
      output.appendLine(`startPos?: TextPosition;`);
      output.appendLine(`endPos?: TextPosition;`);
    }

    for (const [propName, propType] of Object.entries(props.optional)) {
      output.appendLine(`${propName}?: ${propType};`);
    }

    output.appendLine("}");
    output.appendLine();

    output.appendLine(`export function make${name}(`);

    output.indent();
    for (const [propName, propType] of Object.entries(props.required)) {
      output.appendLine(`${propName}: ${propType},`);
    }
    output.appendLine(`optional: Make${name}OptionalProps = {},`);
    output.unindent();

    output.appendLine(`): ${name} {`);

    output.indent();
    output.appendLine("return {");

    output.indent();

    if (name != "Symbol") {
      output.appendLine(`kind: SyntaxKind.${name},`);
      output.appendLine(`startPos: optional.startPos ?? makeTextPosition(0, 0),`);
      output.appendLine(`endPos: optional.endPos ?? makeTextPosition(0, 0),`);
      output.appendLine(`bindState: BindState.Uninitialized,`);
    }

    if (props.extends.includes("Scope")) {
      output.appendLine(`locals: {},`);
      output.appendLine(`nextSymbolScope: null,`);
    }

    for (const propName of Object.keys(props.required)) {
      output.appendLine(`${propName},`);
    }

    for (const propName of Object.keys(props.optional)) {
      output.appendLine(`${propName}: optional.${propName} ?? ${OPTIONAL_DEFAULT_VALUES[propName] ?? "undefined"},`);
    }

    output.unindent();

    output.appendLine("};");
    output.unindent();

    output.appendLine("}");
    output.appendLine();
  }

  await writeAndFormatFile(join(ROOT_PATH, "src", "ast", "factories.ts"), output);
}
