#!/usr/bin/env -S deno run -RW --allow-run
import { join, resolve } from "node:path";
import { EOL } from "node:os";
import { readFile, writeFile } from "node:fs/promises";
import { argv, exit } from "node:process";
import { OutputWriter } from "../src/outputWriter.ts";
import { int } from "../src/shims.ts";
import { firstLetterToLower } from "../src/utils.ts";
import { formatFile } from "./utils.ts";

const ROOT_PATH = resolve(import.meta.dirname!, "..");

main(argv.slice(2)).then(exit);

async function main(_argv: string[]): Promise<int> {
  const syntaxTreeContents = (await readFile(join(ROOT_PATH, "src", "frontend", "ast", "syntaxTree.ts"), "utf-8"))
    .split(EOL)
    .map((x) => x.trim());

  await writeAstTypeGuards(syntaxTreeContents);
  await writeAstWalk(syntaxTreeContents);

  return 0;
}

async function writeAndFormatFile(path: string, output: OutputWriter): Promise<void> {
  await writeFile(path, output.toString());
  await formatFile(path);
}

function createAstOutputWriter(): OutputWriter {
  const output = new OutputWriter();
  output.appendLine("//! This file is autogenerated from syntaxTree.ts.");
  return output;
}

async function writeAstTypeGuards(syntaxTreeContents: string[]): Promise<void> {
  const output = createAstOutputWriter();

  const typeMap: Record<string, string[]> = {};

  for (const line of syntaxTreeContents) {
    if (line.startsWith("export interface ") && !line.endsWith("{}")) {
      const parts = line.split(" ");

      if (parts[3] == "extends") {
        const interfaceName = parts[2];
        const extendedInterfaces = parts.slice(4)
          .filter((x) => x != "{")
          .map((x) => x.endsWith(",") ? x.substring(0, x.length - 1) : x);

        for (const extendedInterface of extendedInterfaces) {
          if (typeMap[extendedInterface] == undefined) {
            typeMap[extendedInterface] = [];
          }

          typeMap[extendedInterface].push(interfaceName);
        }
      }
    }
  }

  const typeGuardsToEmit = ["Expression", "Statement", "TypeNode"];
  output.appendLine(`import { SyntaxKind, SyntaxNode, ${typeGuardsToEmit.join(", ")} } from "./syntaxTree.ts";`);
  output.appendLine();

  for (const typeGuard of typeGuardsToEmit) {
    output.appendLine(`export function is${typeGuard}(node: SyntaxNode): node is ${typeGuard} {`);
    output.indent();

    output.appendLine("return (");
    output.indent();

    const kinds = typeMap[typeGuard].toSorted();

    for (let i = 0; i < kinds.length; i += 1) {
      if (i != 0) {
        output.append("|| ");
      }

      output.appendLine(`node.kind == SyntaxKind.${kinds[i]}`);
    }

    output.unindent();
    output.appendLine(");");

    output.unindent();
    output.appendLine("}");
    output.appendLine();
  }

  await writeAndFormatFile(join(ROOT_PATH, "src", "frontend", "ast", "typeGuards.ts"), output);
}

async function writeAstWalk(syntaxTreeContents: string[]): Promise<void> {
  const output = createAstOutputWriter();

  const importPlaceholder = output.createPlaceholder();
  importPlaceholder.append("import { SyntaxKind, SyntaxNode");

  output.appendLine(
    `import { bool, isError, Result, success } from "../../shims.ts";

export type WalkCallback<Error = unknown> = (node: SyntaxNode, parent?: SyntaxNode) => Result<bool, Error>;

export function walk<Error = unknown>(node: SyntaxNode, callback: WalkCallback<Error>): Result<void, Error> {
  return walkParent<Error>(node, callback);
}

function walkParent<Error = unknown>(
  node: SyntaxNode,
  callback: WalkCallback<Error>,
  parent?: SyntaxNode,
): Result<void, Error> {
  const callbackResult = callback(node, parent);

  if (isError(callbackResult)) {
    return callbackResult;
  }

  // NOTE: The return value of callback indicates if we should keep descending further into the tree.
  if (callbackResult.value) {
    const childrenResult = walkChildren<Error>(node, callback);

    if (isError(childrenResult)) {
      return childrenResult;
    }
  }

  return success();
}

export function walkArray<Error = unknown>(nodes: SyntaxNode[], callback: WalkCallback<Error>): Result<void, Error> {
  return walkArrayParent<Error>(nodes, callback);
}

function walkArrayParent<Error = unknown>(
  nodes: SyntaxNode[],
  callback: WalkCallback<Error>,
  parent?: SyntaxNode,
): Result<void, Error> {
  for (const node of nodes) {
    const result = walkParent<Error>(node, callback, parent);

    if (isError(result)) {
      return result;
    }
  }

  return success();
}

export type WalkChildrenCallback<Error = unknown> = (
  node: SyntaxNode,
  parent: SyntaxNode,
) => Result<bool, Error>;

export function walkChildren<Error = unknown>(
  node: SyntaxNode,
  callback: WalkChildrenCallback<Error>,
): Result<void, Error> {
  let result: Result<void, Error>;
  switch (node.kind) {
`,
  );

  output.indent();
  output.indent();
  let interfaceName: string | null = null;
  let caseBlockIsOutput = false;
  for (const line of syntaxTreeContents) {
    if (interfaceName == null && line.startsWith("export interface ") && !line.endsWith("{}")) {
      const parts = line.split(" ");
      interfaceName = parts[2];

      if (["SyntaxNode", "BlockScope", "Declaration"].includes(interfaceName)) {
        interfaceName = null;
        continue;
      }
    }

    if (interfaceName != null) {
      if (line.startsWith("readonly ")) {
        const parts = line.split(" ");
        let propertyName = parts[1].replaceAll(":", "");

        if (["kind", "exports?", "fileName", "isExported", "operator", "symbol?", "value"].includes(propertyName)) {
          continue;
        }

        const type = parts[2].substring(0, parts[2].length - 1);

        if (type == "string") {
          continue;
        }

        if (!caseBlockIsOutput) {
          output.appendLine(`case SyntaxKind.${interfaceName}: {`);
          output.indent();
          output.appendLine(`const ${firstLetterToLower(interfaceName)} = <${interfaceName}>node;`);
          caseBlockIsOutput = true;

          importPlaceholder.append(`, ${interfaceName}`);
        }

        let isOptional = false;
        if (propertyName.endsWith("?")) {
          propertyName = propertyName.replaceAll("?", "");
          output.appendLine(`if (${firstLetterToLower(interfaceName)}.${propertyName}) {`);
          output.indent();
          isOptional = true;
        }

        let walkFunc = "walkParent";
        if (type.endsWith("[]")) {
          walkFunc = "walkArrayParent";
        }

        output.appendLine(
          `result = ${walkFunc}<Error>(${
            firstLetterToLower(interfaceName)
          }.${propertyName}, <WalkCallback<Error>>callback, ${firstLetterToLower(interfaceName)});`,
        );

        output.appendLine("if (isError(result)) return result;");

        if (isOptional) {
          output.append("}");
          output.unindent();
        }
      } else if (line.startsWith("}")) {
        if (caseBlockIsOutput) {
          output.appendLine("} break;");
          output.unindent();
        }
        interfaceName = null;
        caseBlockIsOutput = false;
      }
    }
  }
  output.unindent();
  output.appendLine("}");
  output.appendLine("return success();");

  output.unindent();
  output.appendLine("}");

  importPlaceholder.append(`} from "./syntaxTree.ts";`);

  await writeAndFormatFile(join(ROOT_PATH, "src", "frontend", "ast", "walk.ts"), output);
}
